version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout

      # Set the JVM heap size to gradle as
      - run: echo "org.gradle.jvmargs=-Xmx2G" >> gradle.properties

      # Download/Install Android SDK for testing
      - run: wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
      - run: unzip -q sdk-tools-linux-4333796.zip
      - run: mkdir $HOME/android-sdk
      - run: mv tools $HOME/android-sdk/tools
      - run: yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses || true

      - run:
          environment:
            ANDROID_HOME: "/home/circleci/android-sdk" # TODO: Try to don't hardcode me and use $HOME env variable
          command: ./gradlew :usekase:test --no-daemon

      - run:
          environment:
            ANDROID_HOME: "/home/circleci/android-sdk" # TODO: Try to don't hardcode me and use $HOME env variable
          command: ./gradlew :usekase-rx:test --no-daemon

      - run:
          environment:
            ANDROID_HOME: "/home/circleci/android-sdk" # TODO: Try to don't hardcode me and use $HOME env variable
          command: ./gradlew :usekase-coroutines:test --no-daemon

      - run:
          environment:
            ANDROID_HOME: "/home/circleci/android-sdk" # TODO: Try to don't hardcode me and use $HOME env variable
          command: ./gradlew :sample:testDebugUnitTest --no-daemon

      - run:
          environment:
            ANDROID_HOME: "/home/circleci/android-sdk" # TODO: Try to don't hardcode me and use $HOME env variable
          command: ./gradlew :sample:testReleaseUnitTest --no-daemon

      - run:
          environment:
            ANDROID_HOME: "/home/circleci/android-sdk" # TODO: Try to don't hardcode me and use $HOME env variable
          command: ./gradlew :usekase-sample:test --no-daemon